### ISSUE TITLE
grsc_linux有问题

### ISSUE THREAD

**Issue by hitushen** [howmp/reality#2]
生成后，grsu_windows.exe可以正常运行，但是grsc_linux提示invalid config length
<img width="860" alt="image" src="https://github.com/user-attachments/assets/b48d1e03-5324-4d32-bbba-bd814f289d68">
<img width="388" alt="image" src="https://github.com/user-attachments/assets/39ca3606-639a-4cc3-b0a6-be3dec9e95c3">

**Comment by hitushen** [comment]
打错了是grsc_windows

**Comment by howmp** [comment]
已解决，原因是占位符太简单，导致配置替换错误

**Comment by hitushen** [comment]
> 已解决，原因是占位符太简单，导致配置替换错误

我本地把判断删了也可以哈哈哈哈
