### ISSUE TITLE
每次运行都会先验证失败一次才建立连接成功

### ISSUE THREAD

**Issue by hitushen** [howmp/reality#3]
<img width="667" alt="image" src="https://github.com/user-attachments/assets/7e4f6130-0da5-4c91-a7af-42f35c5ec7f4">

**Comment by howmp** [comment]
本地无法复现，生成时加-d，然后日志发上来看看

**Comment by howmp** [comment]
已解决，原因是nonce计算的时间错误

**Comment by hitushen** [comment]
> 已解决，原因是nonce计算的时间错误

nb
