### ISSUE TITLE
 verify failed

### ISSUE THREAD

**Issue by DamnVanish** [howmp/reality#4]
我用的时候用客户端和用户端全部都是 verify failed，我换了vps和伪造的域名也都是提示的 verify failed，那个-e 60 也测试了也是 verify failed，请问是有什么需要注意的地方吗

**Comment by howmp** [comment]
1. 检查下各端时间是否一样
2. 服务端开debug，重新生成，把日志发上来

**Comment by DamnVanish** [comment]
生成 命令 ./grss_linux   gen   -e 60  -d www.qq.com:443  x.x.x.x:443

服务端
root@10-9-13-112:/home/vanish/grs# ./grss_linux serv
INFO reality listen :443                          
DEBU random(public for ecdh): 10a667df4ccc7107b74366e288b05540d728bfe867d9256157d1006ffc32f227 
DEBU sessionId(ciphertext): 7f84c764edd7c01b0be4a81716bf4d0c610a4835088141d365b7d54509cdde4d 
DEBU sessionKey: 3814c4902d4c17fd24b226c8b5f5fef0f9330a33324e1f3e052c5e96de77a711 
DEBU nonce: 6a62b3b31233a39f                      
WARN handshake  x.x.x.x:63670 verify failed
cipher: message authentication failed 
DEBU random(public for ecdh): 53e99958f6a46b8da0032859752486b03fa56564eba5d4d139c365069baac66e 
DEBU sessionId(ciphertext): 294cd04d90635584f6e23ccc71404a57cd9b133a129a203cf914b8508a5ee7b9 
DEBU sessionKey: 41628b5b9d14937c266f2366c46e3e7ead67651ae07a0a5a770c27639c9fd320 
DEBU nonce: 021b8948c1a06f7f                      
WARN handshake  x.x.x.x:63874 verify failed
cipher: message authentication failed 
DEBU random(public for ecdh): fe73ed0270fd0f30732c341b144491578ac05b5beea35cae2d04dfc9b12a583d 
DEBU sessionId(ciphertext): 20ad2aa236094739ccc17044ffed154cf64c6a1f4330e7588d35b3f594714067 
DEBU sessionKey: 720618ca7a7c9f6aede01a5c43234c8bfabf4d95df34b005989e7f6f1aa7660b 
DEBU nonce: 32de8f55c1aee309     


客户端                 
C:\Users>grsc0_windows.exe
INFO server addr:  x.x.x.x:443, sni: www.qq.com
INFO try connect to server
DEBU random(public for ecdh): 10a667df4ccc7107b74366e288b05540d728bfe867d9256157d1006ffc32f227
DEBU sessionId(ciphertext): 7f84c764edd7c01b0be4a81716bf4d0c610a4835088141d365b7d54509cdde4d
DEBU sessionKey: 3814c4902d4c17fd24b226c8b5f5fef0f9330a33324e1f3e052c5e96de77a711
DEBU nonce: bb0b83314ceefab4
DEBU plaintext: 5245414c49545963c704abb0d6daadc8
DEBU version: TLS 1.2,cipher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
DEBU overlayData: 0
ERRO serve: verify failed
INFO sleep 5s
INFO try connect to server
DEBU random(public for ecdh): 53e99958f6a46b8da0032859752486b03fa56564eba5d4d139c365069baac66e
DEBU sessionId(ciphertext): 294cd04d90635584f6e23ccc71404a57cd9b133a129a203cf914b8508a5ee7b9
DEBU sessionKey: 41628b5b9d14937c266f2366c46e3e7ead67651ae07a0a5a770c27639c9fd320
DEBU nonce: 6b2b47c657039767
DEBU plaintext: 5245414c495459ddc1ba5b2109bd6d29
DEBU version: TLS 1.2,cipher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
DEBU overlayData: 0
ERRO serve: verify failed

这是时间的问题吗，怎么同步时间

**Comment by howmp** [comment]
nonce不一致，是时间的问题。用ntp同步一下
