### ISSUE TITLE
协议认证失败

### ISSUE THREAD

**Issue by Zer08Bytes** [howmp/reality#5]
![图片](https://github.com/user-attachments/assets/c53eff4d-39ab-4c64-a01c-e9806dc43401)

**Comment by howmp** [comment]
开debug，抓日志上来

**Comment by Zer08Bytes** [comment]
![图片](https://github.com/user-attachments/assets/243f8cf7-f8ab-4180-b766-325e3f1154f8)
这样发你？  eof？

**Comment by howmp** [comment]
<https://github.com/howmp/reality/issues/4>

估计和这个一样，也是服务器和客户端/用户端时间不同步导致

用NTP同步一下时间

**Comment by Zer08Bytes** [comment]
时间一致的。这个不会要求秒也一样吧，我觉得可以优化一下

**Comment by howmp** [comment]
默认要求不能相差30秒

**Comment by Zer08Bytes** [comment]
能优化一下吗？不能相差30秒，是为了防止什么其他问题吗？

**Comment by howmp** [comment]
仔细看下README，可通过参数修改30秒。

为了防止重放，防重放是为了防止被主动探测
