### ISSUE TITLE
成功连接，但无法访问内网资源服务

### ISSUE THREAD

**Issue by IIE-Safety** [howmp/reality#6]
我理解中的
服务器端：作为公网担任服务端，被反连及提供用户端服务；
客户端：被内网穿透出去的主机；
用户端：有需求连进内网服务的主机使用

但是很奇怪，用户端连成功后，无法访问内网资源。想咨询一下，还需要配置其他东西吗？
![1731912209402](https://github.com/user-attachments/assets/5658a794-2771-4851-954f-052b24d1943f)

**Comment by howmp** [comment]
理解没问题，但根据截图你用户端用的id是1，客户端用的id是几呢。

客户端可以看下最初文件名`grscX_***`，X表示id，比如`grsc0_windows.exe`的id是0

客户端和用户端使用相同id才能联通，这个特性是为了方便用户端进入不同的客户端内网

**Comment by IIE-Safety** [comment]
客户端连接的是grsc1_windows.exe，用户端  grsu_windows.exe -i 1
显示会话建立成功，应该是正常建立隧道了。
但是在用户端中，查看公网IP和尝试访问客户端的内网资源，都失败了。

其次，这个能配合proxifer吗？看起来好像不能自定义网络路由。

**Comment by howmp** [comment]
那配置没有问题，用户端默认是监听在61080的socks5代理，当然可以配合proxifer使用

**Comment by IIE-Safety** [comment]
我明白你意思了，接进socks://127.0.0.1:61080，感谢感谢，可以通了
