### ISSUE TITLE
arm架构运行

### ISSUE THREAD

**Issue by hkdonline** [howmp/reality#7]
请问如何编译才能兼容arm架构的..

**Comment by hkdonline** [comment]
修改build.sh文件即可

**Comment by howmp** [comment]
有三端也需要搞一下arm，应该要改下代码，等我空了搞一下

**Comment by fengyeyingxiyang** [comment]
能否编译ARM32位架构

**Comment by howmp** [comment]
> 能否编译ARM32位架构

linux的arm32吗

**Comment by howmp** [comment]
> 能否编译ARM32位架构

https://github.com/howmp/reality/releases/tag/v1.1.4

**Comment by fengyeyingxiyang** [comment]
非常感谢添加arm架构，顺便问一下，有没有什么办法能在安卓手机下运行

**Comment by howmp** [comment]
> 非常感谢添加arm架构，顺便问一下，有没有什么办法能在安卓手机下运行

调java的ProcessBuilder,直接运行就行了
