### ISSUE TITLE
您好，请问是哪里有问题

### ISSUE THREAD

**Issue by donmen5200** [howmp/reality#8]
作者您好，现在是这么个场景，假设我公网vps的ip是123.123.123.123，然后我内网linux的地址是192.168.20.180，现在我想实现socks5代理的话，我是在vps上grss gen -e 60 www.qq.com:443 123.123.123.123:9443,然后我内网linux执行grsc0，我本机执行grsu,然后理论上我用本机的127.0.0.1：61080就可以访问192.168.20.180段了，是这样么？？？我按照上面配置，不行，而且有很多的报错。
ERRO open session stream: session not open
ERRO open session stream: session not open
ERRO connect server: verify failed
INFO sleep 5s
ERRO connect server: verify failed

**Comment by donmen5200** [comment]
后续测试可以了，第一次的时候，我是分别在vps和本机上生成的配置，正确的做法，应该是vps或者攻击机上生成好配置，然后传到对应的服务器上来的，要用一套，而不是各自生成。

**Comment by howmp** [comment]
分别生成会导致预共享密钥不匹配，进而导致验证失败，所以得用一套
