### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote

### ISSUE THREAD

**Issue by Arreb0-1** [howmp/reality#9]
师傅麻烦问一下以下是什么原因，vps的端口是开放的
![微信截图_20241212175346](https://github.com/user-attachments/assets/2c1f9f9e-de3c-4589-a51c-241b4c9282dc)
[
![微信截图_20241212175453](https://github.com/user-attachments/assets/a8c5fdcf-bc4b-46a9-9e95-3764179b825c)
](url)

**Comment by howmp** [comment]
看起来是连接成功，recv的时候失败。你发服务端日志上来看看
